# Generated by Django 6.1 on 2026-10-04 15:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector",
            reverse_sql="DROP EXTENSION IF EXISTS vector",
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('slug', models.TextField(primary_key=True, serialize=False)),
                ('collection', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('websites', models.JSONField(blank=True, null=True)),
                ('api', models.JSONField(blank=True, null=True)),
                ('dataset', models.JSONField(blank=True, null=True)),
                ('page_last_updated', models.TextField(blank=True, null=True)),
                ('visualisation_data', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(db_default=0)),
                ('related_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection_pages',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ckan_id', models.TextField(unique=True)),
                ('org_slug', models.TextField()),
                ('org_display_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata_created', models.TextField(blank=True, null=True)),
                ('metadata_modified', models.TextField(blank=True, null=True)),
                ('resource_count', models.IntegerField(blank=True, null=True)),
                ('theme_primary', models.TextField(blank=True, null=True)),
                ('harvested', models.IntegerField(db_default=0)),
                ('harvest_source_title', models.TextField(blank=True, null=True)),
                ('harvest_source_id', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(db_default=0)),
                ('tags', models.TextField(blank=True, null=True)),
                ('fts', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='DatasetEmbedding',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
            ],
            options={
                'db_table': 'dataset_embeddings',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingMap',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'embedding_map',
            },
        ),
        migrations.CreateModel(
            name='HarvestSource',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('organization_id', models.TextField(blank=True, null=True)),
                ('org_slug', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'harvest_sources',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.TextField(blank=True, null=True)),
                ('org_slug', models.TextField()),
                ('org_display_name', models.TextField(blank=True, null=True)),
                ('dataset_title', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('format_norm', models.TextField(blank=True, null=True)),
                ('year_created', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='LinkCheckResult',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('ok', models.BooleanField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('final_url', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_check_results',
            },
        ),
        migrations.CreateModel(
            name='MetadataKey',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('section', models.TextField()),
                ('count', models.IntegerField()),
                ('non_empty', models.IntegerField()),
                ('distinct_values', models.IntegerField()),
            ],
            options={
                'db_table': 'metadata_keys',
            },
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('metadata_key', models.ForeignKey(db_column='key', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.metadatakey')),
                ('value', models.TextField()),
                ('count', models.IntegerField()),
                ('pk', models.CompositePrimaryKey('metadata_key', 'value', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'metadata_values',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('slug', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('package_count', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('approval_status', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='RelatedDataset',
            fields=[
                ('dataset_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
                ('pk', models.CompositePrimaryKey('dataset_id', 'rank', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'related_datasets',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('findability', models.IntegerField(blank=True, null=True)),
                ('resources', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('json', models.TextField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('root_title', models.TextField()),
                ('type', models.TextField()),
                ('dataset_count', models.IntegerField(db_default=0)),
                ('org_count', models.IntegerField(db_default=0)),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='SeriesDataset',
            fields=[
                ('series', models.ForeignKey(db_column='series_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.series')),
                ('dataset_id', models.IntegerField()),
                ('dataset_title', models.TextField()),
                ('date_suffix', models.TextField(blank=True, null=True)),
                ('org_slug', models.TextField()),
                ('org_display_name', models.TextField()),
                ('pk', models.CompositePrimaryKey('series', 'dataset_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'series_datasets',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.TextField(blank=True, null=True)),
                ('theme_confidence', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('json', models.TextField()),
            ],
            options={
                'db_table': 'suggestions',
            },
        ),
        migrations.CreateModel(
            name='TemporalPeriod',
            fields=[
                ('dataset', models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.dataset')),
                ('position', models.IntegerField()),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField()),
                ('pk', models.CompositePrimaryKey('dataset', 'position', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'temporal_periods',
            },
        ),
        migrations.CreateModel(
            name='CollectionEmbedding',
            fields=[
                ('slug', models.OneToOneField(db_column='slug', db_index=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='explorer.collection')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                'db_table': 'collection_embeddings',
            },
        ),
        migrations.CreateModel(
            name='CollectionRelatedDataset',
            fields=[
                ('rank', models.IntegerField()),
                ('distance', models.FloatField()),
                ('pk', models.CompositePrimaryKey('slug', 'rank', blank=True, editable=False, primary_key=True, serialize=False)),
                ('slug', models.ForeignKey(db_column='slug', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.collection')),
            ],
            options={
                'db_table': 'collection_related_datasets',
            },
        ),
        migrations.CreateModel(
            name='DatasetApi',
            fields=[
                ('dataset', models.OneToOneField(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='explorer.dataset')),
                ('api_category', models.TextField()),
            ],
            options={
                'db_table': 'dataset_api',
            },
        ),
        migrations.CreateModel(
            name='DatasetContentHash',
            fields=[
                ('dataset', models.OneToOneField(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='explorer.dataset')),
                ('content_hash', models.TextField()),
            ],
            options={
                'db_table': 'dataset_content_hash',
            },
        ),
        migrations.CreateModel(
            name='DatasetJson',
            fields=[
                ('dataset', models.OneToOneField(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='explorer.dataset')),
                ('json', models.JSONField()),
            ],
            options={
                'db_table': 'dataset_json',
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['org_slug'], name='idx_datasets_org'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['org_slug', 'resource_count'], name='idx_datasets_org_resource'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['theme_primary'], name='idx_datasets_theme'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['metadata_created'], name='idx_datasets_created'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['metadata_modified'], name='idx_datasets_modified'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['-views'], name='idx_datasets_views_desc'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['ckan_id'], include=('org_slug', 'org_display_name', 'title', 'theme_primary'), name='idx_datasets_ckan_id_cover'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts'], name='idx_datasets_fts'),
        ),
        migrations.AddField(
            model_name='collectionrelateddataset',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='explorer.dataset'),
        ),
        migrations.AddIndex(
            model_name='datasetembedding',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='idx_dataset_embeddings_hnsw', opclasses=['vector_l2_ops']),
        ),
        migrations.AddField(
            model_name='embeddingmap',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.dataset'),
        ),
        migrations.AddField(
            model_name='link',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.dataset'),
        ),
        migrations.AddIndex(
            model_name='linkcheckresult',
            index=models.Index(fields=['url'], include=('ok', 'http_status', 'error', 'checked_at'), name='idx_lcr_url_cover'),
        ),
        migrations.AddField(
            model_name='relateddataset',
            name='related',
            field=models.ForeignKey(db_column='related_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='explorer.dataset'),
        ),
        migrations.AddField(
            model_name='review',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.dataset'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ('template', 'timeseries'))), name='series_type_check'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.dataset'),
        ),
        migrations.AddIndex(
            model_name='datasetapi',
            index=models.Index(fields=['api_category'], name='dataset_api_category_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetcontenthash',
            index=models.Index(fields=['content_hash'], name='dataset_content_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingmap',
            index=models.Index(fields=['dataset'], name='idx_embedding_map_dataset'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['host'], name='idx_links_host'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['format_norm'], name='idx_links_format'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['year_created'], name='idx_links_year'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['dataset'], name='idx_links_dataset'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['org_slug'], name='idx_links_org'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(condition=models.Q(('url__isnull', False), models.Q(('url', ''), _negated=True)), fields=['url', 'dataset', 'org_slug'], name='idx_links_url_dataset_org'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(django.db.models.functions.text.Lower(django.db.models.functions.comparison.Coalesce('host', models.Value(''))), name='idx_links_host_lower'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('dataset',), include=('findability', 'resources'), name='uniq_reviews_dataset'),
        ),
        migrations.AddIndex(
            model_name='seriesdataset',
            index=models.Index(fields=['series'], name='idx_series_datasets_series'),
        ),
        migrations.AddIndex(
            model_name='seriesdataset',
            index=models.Index(fields=['dataset_id'], name='idx_series_datasets_dataset'),
        ),
        migrations.AddConstraint(
            model_name='suggestion',
            constraint=models.UniqueConstraint(fields=('dataset',), include=('theme', 'theme_confidence', 'tags', 'title', 'desc'), name='uniq_suggestions_dataset'),
        ),
    ]
