# Generated by Django 6.1 on 2026-09-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='review',
            name='overall',
        ),
    ]
