# Generated by Django 6.1 on 2026-10-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_squash_indexes_remove_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='related_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollectionRelatedDataset',
            fields=[
                ('rank', models.IntegerField()),
                ('distance', models.FloatField()),
                ('pk', models.CompositePrimaryKey('slug', 'rank', blank=True, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.ForeignKey(db_column='dataset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='explorer.dataset')),
                ('slug', models.ForeignKey(db_column='slug', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='explorer.collection')),
            ],
            options={
                'db_table': 'collection_related_datasets',
            },
        ),
        migrations.CreateModel(
            name='RelatedDataset',
            fields=[
                ('dataset_id', models.TextField()),
                ('source', models.TextField()),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
                ('pk', models.CompositePrimaryKey('dataset_id', 'source', 'rank', blank=True, editable=False, primary_key=True, serialize=False)),
                ('related', models.ForeignKey(db_column='related_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='explorer.dataset')),
            ],
            options={
                'db_table': 'related_datasets',
            },
        ),
    ]
