# Generated by Django 6.1 on 2026-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_baked_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relateddataset',
            name='source',
        ),
        migrations.AlterField(
            model_name='relateddataset',
            name='pk',
            field=models.CompositePrimaryKey('dataset_id', 'rank', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
