# Generated by Django 6.1 on 2026-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_link_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetjson',
            name='json',
            field=models.JSONField(),
        ),
    ]
